// AI工具数据源
const aiToolsData = [
    // 文本生成类
    {
        id: 1,
        name: "ChatGPT",
        description: "OpenAI开发的大型语言模型，支持多轮对话、代码编写、文章创作等多种任务，是目前最流行的AI助手之一。",
        category: "text",
        subcategory: "对话助手",
        icon: "fab fa-rocketchat",
        iconColor: "#10a37f",
        pricing: "freemium",
        rating: 4.9,
        reviews: 125000,
        website: "https://chat.openai.com",
        tags: ["对话", "写作", "代码", "翻译"],
        features: ["多轮对话", "代码生成", "文本创作", "知识问答"],
        popularity: 100
    },
    {
        id: 2,
        name: "Claude",
        description: "Anthropic开发的AI助手，以其出色的长文本处理能力和安全性著称，特别擅长分析、总结和创意写作。",
        category: "text",
        subcategory: "对话助手",
        icon: "fas fa-comment-alt",
        iconColor: "#d4a574",
        pricing: "freemium",
        rating: 4.8,
        reviews: 85000,
        website: "https://claude.ai",
        tags: ["对话", "分析", "写作", "安全"],
        features: ["长文本处理", "安全性高", "创意写作", "文档分析"],
        popularity: 95
    },
    {
        id: 3,
        name: "Gemini",
        description: "Google开发的下一代AI模型，支持文本、图像、视频等多种模态输入，拥有强大的多模态处理能力。",
        category: "text",
        subcategory: "多模态AI",
        icon: "fas fa-gem",
        iconColor: "#06b6d4",
        pricing: "freemium",
        rating: 4.7,
        reviews: 72000,
        website: "https://gemini.google.com",
        tags: ["多模态", "搜索", "创作", "分析"],
        features: ["多模态理解", "Google集成", "高效处理", "创意生成"],
        popularity: 92
    },
    {
        id: 4,
        name: "文心一言",
        description: "百度开发的中文大语言模型，擅长中文理解和生成，提供丰富的API接口和企业级服务。",
        category: "text",
        subcategory: "中文AI",
        icon: "fas fa-dragon",
        iconColor: "#3b82f6",
        pricing: "freemium",
        rating: 4.6,
        reviews: 65000,
        website: "https://yiyan.baidu.com",
        tags: ["中文", "对话", "创作", "企业"],
        features: ["中文优化", "企业服务", "API丰富", "知识增强"],
        popularity: 90
    },
    {
        id: 5,
        name: "通义千问",
        description: "阿里巴巴开发的大语言模型，支持多轮对话、知识问答、代码编写等功能，提供通义家族产品矩阵。",
        category: "text",
        subcategory: "中文AI",
        icon: "fas fa-cloud",
        iconColor: "#ff6b6b",
        pricing: "freemium",
        rating: 4.5,
        reviews: 58000,
        website: "https://tongyi.aliyun.com",
        tags: ["中文", "对话", "阿里生态", "多模态"],
        features: ["阿里生态", "多模态", "企业级", "API服务"],
        popularity: 88
    },
    {
        id: 6,
        name: "讯飞星火",
        description: "科大讯飞开发的认知大模型，在中文理解和生成方面有独特优势，支持多领域应用场景。",
        category: "text",
        subcategory: "中文AI",
        icon: "fas fa-fire",
        iconColor: "#7c3aed",
        pricing: "freemium",
        rating: 4.5,
        reviews: 52000,
        website: "https://xinghuo.xfyun.cn",
        tags: ["中文", "语音", "教育", "医疗"],
        features: ["语音处理", "教育应用", "多领域", "语音合成"],
        popularity: 85
    },
    {
        id: 7,
        name: "Copilot",
        description: "Microsoft和OpenAI合作开发的AI助手，深度集成于Microsoft 365套件，提供智能办公辅助。",
        category: "text",
        subcategory: "办公助手",
        icon: "fas fa-copilot",
        iconColor: "#0078d4",
        pricing: "paid",
        rating: 4.7,
        reviews: 68000,
        website: "https://copilot.microsoft.com",
        tags: ["办公", "Microsoft", "效率", "协作"],
        features: ["Office集成", "智能写作", "数据分析", "会议助手"],
        popularity: 91
    },
    {
        id: 8,
        name: "Jasper",
        description: "专注于营销内容生成的AI平台，帮助企业快速创建博客、社交媒体、广告文案等营销材料。",
        category: "text",
        subcategory: "营销写作",
        icon: "fas fa-pen-fancy",
        iconColor: "#f43f5e",
        pricing: "paid",
        rating: 4.5,
        reviews: 45000,
        website: "https://jasper.ai",
        tags: ["营销", "内容创作", "SEO", "品牌"],
        features: ["营销模板", "品牌声音", "SEO优化", "多语言"],
        popularity: 82
    },
    {
        id: 9,
        name: "Notion AI",
        description: "Notion内置的AI功能，帮助用户优化写作、总结笔记、生成内容，提升工作效率。",
        category: "text",
        subcategory: "办公助手",
        icon: "fas fa-not-equal",
        iconColor: "#1a1a1a",
        pricing: "paid",
        rating: 4.6,
        reviews: 55000,
        website: "https://notion.so/ai",
        tags: ["笔记", "办公", "协作", "知识管理"],
        features: ["笔记优化", "内容生成", "任务管理", "智能搜索"],
        popularity: 86
    },
    {
        id: 10,
        name: "Grammarly AI",
        description: "AI驱动的写作助手，提供语法检查、风格优化、语气调整等功能，帮助用户写出更好的英文内容。",
        category: "text",
        subcategory: "写作辅助",
        icon: "fas fa-pen-nib",
        iconColor: "#15c39a",
        pricing: "freemium",
        rating: 4.8,
        reviews: 95000,
        website: "https://grammarly.com",
        tags: ["语法", "写作", "英语", "校对"],
        features: ["语法检查", "风格建议", "语气调整", "抄袭检测"],
        popularity: 93
    },
    
    // 图像生成类
    {
        id: 11,
        name: "Midjourney",
        description: "最强AI图像生成器之一，以其艺术性和审美水平著称，适合创作插画、概念设计、艺术作品。",
        category: "image",
        subcategory: "图像生成",
        icon: "fas fa-palette",
        iconColor: "#9d4edd",
        pricing: "paid",
        rating: 4.9,
        reviews: 88000,
        website: "https://midjourney.com",
        tags: ["艺术", "插画", "设计", "创意"],
        features: ["高质量图像", "艺术风格", "社区分享", "参数丰富"],
        popularity: 98
    },
    {
        id: 12,
        name: "DALL-E 3",
        description: "OpenAI开发的图像生成模型，能够根据文字描述生成高度详细的图像，支持复杂的构图和细节。",
        category: "image",
        subcategory: "图像生成",
        icon: "fas fa-paint-brush",
        iconColor: "#f59e0b",
        pricing: "paid",
        rating: 4.7,
        reviews: 75000,
        website: "https://openai.com/dall-e-3",
        tags: ["图像生成", "创意", "设计", "ChatGPT集成"],
        features: ["ChatGPT集成", "高细节", "文本理解", "版权保护"],
        popularity: 94
    },
    {
        id: 13,
        name: "Stable Diffusion",
        description: "开源的AI图像生成模型，支持本地部署和定制训练，拥有庞大的社区和丰富模型资源。",
        category: "image",
        subcategory: "开源图像",
        icon: "fas fa-layer-group",
        iconColor: "#ef4444",
        pricing: "free",
        rating: 4.6,
        reviews: 92000,
        website: "https://stability.ai",
        tags: ["开源", "本地部署", "自定义", "免费"],
        features: ["开源免费", "高度可定制", "社区丰富", "本地运行"],
        popularity: 96
    },
    {
        id: 14,
        name: "Adobe Firefly",
        description: "Adobe开发的创意AI工具，深度集成于Photoshop、Illustrator等Adobe产品，支持生成式填充和编辑。",
        category: "image",
        subcategory: "设计工具",
        icon: "fas fa-bolt",
        iconColor: "#ff0000",
        pricing: "freemium",
        rating: 4.6,
        reviews: 62000,
        website: "https://firefly.adobe.com",
        tags: ["Adobe", "设计", "编辑", "创意"],
        features: ["Adobe集成", "生成填充", "文字生成图像", "商业安全"],
        popularity: 89
    },
    {
        id: 15,
        name: "Leonardo AI",
        description: "功能强大的AI图像生成平台，提供实时生成、模型训练、ControlNet控制等功能。",
        category: "image",
        subcategory: "图像生成",
        icon: "fas fa-magic",
        iconColor: "#06c755",
        pricing: "freemium",
        rating: 4.7,
        reviews: 48000,
        website: "https://leonardo.ai",
        tags: ["实时生成", "ControlNet", "模型训练"],
        features: ["实时生成", "模型训练", "ControlNet", "社区分享"],
        popularity: 87
    },
    {
        id: 16,
        name: "Canva AI",
        description: "Canva内置的AI设计功能，支持AI图像生成、背景移除、智能设计建议等。",
        category: "image",
        subcategory: "设计工具",
        icon: "fas fa-crop-alt",
        iconColor: "#00c4cc",
        pricing: "freemium",
        rating: 4.5,
        reviews: 72000,
        website: "https://canva.com",
        tags: ["设计", "模板", "社交媒体", "演示文稿"],
        features: ["海量模板", "AI图像生成", "背景移除", "协作编辑"],
        popularity: 88
    },
    {
        id: 17,
        name: "Runway ML",
        description: "创意AI平台，支持图像生成、视频生成、图像编辑等多种功能，Gen-2视频生成效果出色。",
        category: "image",
        subcategory: "创意AI",
        icon: "fas fa-film",
        iconColor: "#ff2d55",
        pricing: "freemium",
        rating: 4.6,
        reviews: 55000,
        website: "https://runwayml.com",
        tags: ["视频", "图像", "编辑", "创意"],
        features: ["视频生成", "图像编辑", "背景去除", "团队协作"],
        popularity: 85
    },
    {
        id: 18,
        name: "Pika Labs",
        description: "专注于AI视频生成的平台，能够根据文字描述或图片生成高质量的短视频内容。",
        category: "image",
        subcategory: "视频生成",
        icon: "fas fa-video",
        iconColor: "#8b5cf6",
        pricing: "freemium",
        rating: 4.5,
        reviews: 42000,
        website: "https://pika.art",
        tags: ["视频", "AI生成", "创意", "社交"],
        features: ["文本转视频", "图像转视频", "视频编辑", "社区分享"],
        popularity: 84
    },
    
    // 代码辅助类
    {
        id: 19,
        name: "GitHub Copilot",
        description: "GitHub和OpenAI合作开发的AI编程助手，支持多种编程语言，提供代码补全、生成、解释等功能。",
        category: "code",
        subcategory: "代码助手",
        icon: "fab fa-github",
        iconColor: "#f0f0f0",
        pricing: "paid",
        rating: 4.8,
        reviews: 115000,
        website: "https://github.com/features/copilot",
        tags: ["编程", "代码补全", "GitHub", "IDE集成"],
        features: ["代码补全", "多语言支持", "IDE集成", "上下文理解"],
        popularity: 99
    },
    {
        id: 20,
        name: "Cursor",
        description: "AI优先的代码编辑器，基于VS Code构建，提供智能代码编辑、重构、调试等高级功能。",
        category: "code",
        subcategory: "代码编辑器",
        icon: "fas fa-code",
        iconColor: "#3b82f6",
        pricing: "freemium",
        rating: 4.9,
        reviews: 58000,
        website: "https://cursor.sh",
        tags: ["编辑器", "AI编程", "重构", "调试"],
        features: ["AI编辑", "代码重构", "智能调试", "上下文感知"],
        popularity: 94
    },
    {
        id: 21,
        name: "Codeium",
        description: "免费的AI编程助手，提供代码补全、生成、解释功能，支持多种主流编程语言和IDE。",
        category: "code",
        subcategory: "代码助手",
        icon: "fas fa-code-branch",
        iconColor: "#22c55e",
        pricing: "free",
        rating: 4.6,
        reviews: 48000,
        website: "https://codeium.com",
        tags: ["免费", "编程", "代码补全", "多语言"],
        features: ["完全免费", "代码补全", "代码解释", "多IDE支持"],
        popularity: 88
    },
    {
        id: 22,
        name: "Tabnine",
        description: "AI代码补全工具，支持私有部署，保护代码隐私，提供个性化的代码建议。",
        category: "code",
        subcategory: "代码助手",
        icon: "fas fa-tablet-alt",
        iconColor: "#06b6d4",
        pricing: "freemium",
        rating: 4.5,
        reviews: 42000,
        website: "https://tabnine.com",
        tags: ["代码补全", "隐私保护", "私有部署"],
        features: ["代码补全", "隐私安全", "个性化", "多语言"],
        popularity: 82
    },
    {
        id: 23,
        name: "Replit AI",
        description: "Replit在线编程平台的AI功能，支持代码生成、解释、调试，提供协作编程体验。",
        category: "code",
        subcategory: "在线编程",
        icon: "fas fa-play-circle",
        iconColor: "#6366f1",
        pricing: "freemium",
        rating: 4.5,
        reviews: 38000,
        website: "https://replit.com",
        tags: ["在线编程", "协作", "学习", "部署"],
        features: ["在线运行", "协作编程", "AI助手", "多语言"],
        popularity: 80
    },
    {
        id: 24,
        name: "Amazon CodeWhisperer",
        description: "亚马逊开发的AI编程助手，提供代码建议、安全扫描、AWS集成等功能。",
        category: "code",
        subcategory: "代码助手",
        icon: "fab fa-amazon",
        iconColor: "#ff9900",
        pricing: "free",
        rating: 4.4,
        reviews: 35000,
        website: "https://aws.amazon.com/codewhisperer",
        tags: ["AWS", "云服务", "代码安全", "免费"],
        features: ["AWS集成", "安全扫描", "代码建议", "免费使用"],
        popularity: 78
    },
    
    // 视频生成类
    {
        id: 25,
        name: "Sora",
        description: "OpenAI开发的文本到视频AI模型，能够生成长达60秒的高质量视频，支持复杂场景和角色。",
        category: "video",
        subcategory: "视频生成",
        icon: "fas fa-video-slash",
        iconColor: "#8b5cf6",
        pricing: "paid",
        rating: 4.8,
        reviews: 68000,
        website: "https://openai.com/sora",
        tags: ["视频生成", "长视频", "文本转视频", "OpenAI"],
        features: ["长视频生成", "复杂场景", "物理模拟", "角色一致"],
        popularity: 97
    },
    {
        id: 26,
        name: "Runway Gen-2",
        description: "Runway的第二代视频生成模型，支持文本到视频、图像到视频、视频到视频等多种模式。",
        category: "video",
        subcategory: "视频生成",
        icon: "fas fa-forward",
        iconColor: "#ff2d55",
        pricing: "paid",
        rating: 4.6,
        reviews: 52000,
        website: "https://runwayml.com/gen-2",
        tags: ["视频生成", "多模式", "创意", "专业"],
        features: ["多模式生成", "视频编辑", "运动控制", "高质量输出"],
        popularity: 90
    },
    {
        id: 27,
name: "Pika Labs",
        description: "新兴的AI视频生成平台，以其易用性和快速生成速度著称，适合社交媒体内容创作。",
        category: "video",
        subcategory: "视频生成",
        icon: "fas fa-bolt",
        iconColor: "#f59e0b",
        pricing: "freemium",
        rating: 4.5,
        reviews: 45000,
        website: "https://pika.art",
        tags: ["AI视频", "快速生成", "社交媒体", "创意"],
        features: ["快速生成", "易用性强", "社区活跃", "免费额度"],
        popularity: 86
    },
    {
        id: 28,
        name: "Synthesia",
        description: "AI视频生成平台，可以创建虚拟人主持的AI视频，支持多种语言和自定义虚拟形象。",
        category: "video",
        subcategory: "虚拟人视频",
        icon: "fas fa-user-astronaut",
        iconColor: "#3b82f6",
        pricing: "paid",
        rating: 4.5,
        reviews: 38000,
        website: "https://synthesia.io",
        tags: ["虚拟人", "企业视频", "培训", "多语言"],
        features: ["虚拟人", "企业应用", "多语言", "模板丰富"],
        popularity: 82
    },
    {
        id: 29,
        name: "HeyGen",
        description: "AI视频翻译和虚拟人平台，支持将视频翻译成多种语言，同时保持原说话者的声音和表情。",
        category: "video",
        subcategory: "视频翻译",
        icon: "fas fa-language",
        iconColor: "#10b981",
        pricing: "paid",
        rating: 4.6,
        reviews: 32000,
        website: "https://heygen.com",
        tags: ["视频翻译", "虚拟人", "多语言", "企业"],
        features: ["AI翻译", "声音克隆", "表情保持", "企业级"],
        popularity: 80
    },
    
    // 音频生成类
    {
        id: 30,
        name: "ElevenLabs",
        description: "AI语音生成平台，提供高质量的文字转语音和语音克隆服务，支持多种语言和声音风格。",
        category: "audio",
        subcategory: "语音合成",
        icon: "fas fa-volume-up",
        iconColor: "#06b6d4",
        pricing: "freemium",
        rating: 4.8,
        reviews: 65000,
        website: "https://elevenlabs.io",
        tags: ["语音合成", "语音克隆", "多语言", "有声书"],
        features: ["高质量语音", "语音克隆", "多语言", "声音库"],
        popularity: 92
    },
    {
        id: 31,
        name: "Mubert",
        description: "AI音乐生成平台，可以根据情绪、节奏等参数生成免版税的背景音乐。",
        category: "audio",
        subcategory: "音乐生成",
        icon: "fas fa-music",
        iconColor: "#8b5cf6",
        pricing: "freemium",
        rating: 4.6,
        reviews: 45000,
        website: "https://mubert.com",
        tags: ["音乐生成", "免版税", "背景音乐", "情绪"],
        features: ["AI作曲", "免版税", "情绪控制", "API支持"],
        popularity: 85
    },
    {
        id: 32,
        name: "Suno AI",
        description: "AI音乐生成工具，可以根据文字描述生成完整的音乐作品，包括歌词、旋律和演唱。",
        category: "audio",
        subcategory: "音乐生成",
        icon: "fas fa-guitar",
        iconColor: "#f43f5e",
        pricing: "freemium",
        rating: 4.7,
        reviews: 55000,
        website: "https://suno.ai",
        tags: ["音乐生成", "歌曲创作", "AI歌手", "创意"],
        features: ["完整歌曲", "歌词生成", "多风格", "高质量"],
        popularity: 91
    },
    {
        id: 33,
        name: "Whisper",
        description: "OpenAI开发的语音识别模型，支持多语言语音转文字，准确率高，支持实时转录。",
        category: "audio",
        subcategory: "语音识别",
        icon: "fas fa-microphone-alt",
        iconColor: "#10a37f",
        pricing: "free",
        rating: 4.7,
        reviews: 78000,
        website: "https://openai.com/research/whisper",
        tags: ["语音识别", "转文字", "多语言", "开源"],
        features: ["高准确率", "多语言", "开源免费", "实时转录"],
        popularity: 93
    },
    {
        id: 34,
        name: "Adobe Podcast",
        description: "Adobe推出的AI音频增强工具，可以自动消除录音中的背景噪音和回声，提升音质。",
        category: "audio",
        subcategory: "音频处理",
        icon: "fas fa-podcast",
        iconColor: "#ff0000",
        pricing: "freemium",
        rating: 4.5,
        reviews: 38000,
        website: "https://podcast.adobe.com",
        tags: ["音频增强", "降噪", "播客", "Adobe"],
        features: ["AI降噪", "音质提升", "免费使用", "网页版"],
        popularity: 80
    },
    
    // 3D建模类
    {
        id: 35,
        name: "Luma AI",
        description: "AI 3D建模平台，可以从文本或图片生成3D模型，支持神经辐射场和3D场景创建。",
        category: "3d",
        subcategory: "3D生成",
        icon: "fas fa-cube",
        iconColor: "#8b5cf6",
        pricing: "freemium",
        rating: 4.6,
        reviews: 42000,
        website: "https://lumalabs.ai",
        tags: ["3D建模", "神经辐射场", "场景创建", "AI"],
        features: ["文本转3D", "图像转3D", "场景生成", "API支持"],
        popularity: 86
    },
    {
        id: 36,
        name: "Meshy",
        description: "AI 3D建模工具，专门为游戏和VR/AR开发者设计，可以快速生成游戏资产。",
        category: "3d",
        subcategory: "游戏资产",
        icon: "fas fa-gamepad",
        iconColor: "#22c55e",
        pricing: "freemium",
        rating: 4.4,
        reviews: 28000,
        website: "https://meshy.ai",
        tags: ["3D建模", "游戏资产", "VR/AR", "快速生成"],
        features: ["游戏资产", "VR/AR支持", "快速生成", "导出多种格式"],
        popularity: 75
    },
    {
        id: 37,
        name: "CSM",
        description: "Common Sense Machines，提供AI辅助的3D建模和设计工具，帮助设计师快速原型化。",
        category: "3d",
        subcategory: "设计工具",
        icon: "fas fa-shapes",
        iconColor: "#f59e0b",
        pricing: "freemium",
        rating: 4.3,
        reviews: 25000,
        website: "https://csm.ai",
        tags: ["3D设计", "原型设计", "AI辅助", "设计师"],
        features: ["AI辅助设计", "快速原型", "协作功能", "导出支持"],
        popularity: 72
    },
    
    // 搜索和研究类
    {
        id: 38,
        name: "Perplexity AI",
        description: "AI驱动的搜索引擎，提供对话式搜索体验，能够理解复杂问题并提供带有来源的答案。",
        category: "text",
        subcategory: "AI搜索",
        icon: "fas fa-search",
        iconColor: "#6366f1",
        pricing: "freemium",
        rating: 4.7,
        reviews: 68000,
        website: "https://perplexity.ai",
        tags: ["AI搜索", "研究助手", "知识问答", "引用来源"],
        features: ["对话式搜索", "来源引用", "研究助手", "实时信息"],
        popularity: 90
    },
    {
        id: 39,
        name: "Elicit",
        description: "AI研究助手，可以自动搜索论文、总结摘要、提取关键信息，加速学术研究过程。",
        category: "text",
        subcategory: "研究助手",
        icon: "fas fa-flask",
        iconColor: "#3b82f6",
        pricing: "freemium",
        rating: 4.5,
        reviews: 35000,
        website: "https://elicit.org",
        tags: ["学术研究", "论文搜索", "文献综述", "AI助手"],
        features: ["论文搜索", "自动摘要", "文献综述", "研究问题"],
        popularity: 78
    },
    
    // 数据分析和商业智能
    {
        id: 40,
        name: "Tableau Pulse",
        description: "Tableau的AI驱动的数据洞察功能，提供自然语言查询和自动数据可视化分析。",
        category: "text",
        subcategory: "数据分析",
        icon: "fas fa-chart-bar",
        iconColor: "#e11d48",
        pricing: "paid",
        rating: 4.5,
        reviews: 32000,
        website: "https://tableau.com",
        tags: ["数据分析", "可视化", "商业智能", "AI"],
        features: ["自然语言查询", "自动可视化", "数据洞察", "企业级"],
        popularity: 76
    },
    {
        id: 41,
        name: "GitHub Copilot X",
        description: "GitHub Copilot的进化版，增加聊天界面、文档理解、PR描述等高级AI编程功能。",
        category: "code",
        subcategory: "AI编程",
        icon: "fab fa-github",
        iconColor: "#f0f0f0",
        pricing: "paid",
        rating: 4.8,
        reviews: 52000,
        website: "https://github.com/features/copilot",
        tags: ["AI编程", "聊天界面", "文档理解", "PR描述"],
        features: ["AI聊天", "文档理解", "PR描述", "测试生成"],
        popularity: 92
    }
];

// 分类信息
const categoryInfo = {
    text: {
        name: "文本生成",
        icon: "fas fa-file-alt",
        description: "大型语言模型和对话AI，帮助您完成写作、分析、创作等任务",
        count: 20,
        gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
    },
    image: {
        name: "图像生成",
        icon: "fas fa-image",
        description: "AI图像生成和编辑工具，将文字转化为惊艳的视觉作品",
        count: 12,
        gradient: "linear-gradient(135deg, #f093fb 0%, #f5576c 100%)"
    },
    video: {
        name: "视频生成",
        icon: "fas fa-video",
        description: "AI视频创作平台，快速生成专业级视频内容",
        count: 8,
        gradient: "linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)"
    },
    code: {
        name: "代码辅助",
        icon: "fas fa-code",
        description: "AI编程助手，提升开发效率，让代码编写更轻松",
        count: 10,
        gradient: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)"
    },
    audio: {
        name: "音频生成",
        icon: "fas fa-music",
        description: "AI语音合成和音乐生成工具，创造高质量音频内容",
        count: 8,
        gradient: "linear-gradient(135deg, #43e97b 0%, #38f9d7 100%)"
    },
    "3d": {
        name: "3D建模",
        icon: "fas fa-cube",
        description: "AI驱动的3D建模和设计工具，快速创建3D资产",
        count: 5,
        gradient: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)"
    }
};

// 提示词模板
const promptTemplates = [
    {
        category: "写作",
        title: "文章生成",
        description: "生成高质量的文章、博客、报道",
        prompt: "请写一篇关于{topic}的深度文章，要求：\n1. 开头引人入胜，设置悬念或提出问题\n2. 包含2-3个实际案例来支撑观点\n3. 结构清晰，包含引言、主体、结论\n4. 提供独特的洞见和分析\n5. 字数800-1200字\n6. 语言风格：{style}"
    },
    {
        category: "设计",
        title: "Logo设计",
        description: "AI辅助设计Logo和品牌标识",
        prompt: "设计一个关于{brand}的Logo，要求：\n1. 简洁现代的设计风格\n2. 体现{industry}行业的特点\n3. 使用{colors}配色方案\n4. 适合各种尺寸和场景\n5. 考虑在深色和浅色背景下的表现\n6. 提供设计理念说明"
    },
    {
        category: "编程",
        title: "代码生成",
        description: "生成各种编程语言的代码",
        prompt: "用{language}实现一个{function}功能，要求：\n1. 代码结构清晰，命名规范\n2. 添加详细的注释说明\n3. 包含适当的错误处理\n4. 提供使用示例\n5. 考虑性能优化\n6. 遵循最佳实践"
    },
    {
        category: "创意",
        title: "故事创作",
        description: "创作引人入胜的故事和小说",
        prompt: "创作一个关于{theme}的短故事，要求：\n1. 开头引人入胜，抓住读者注意力\n2. 塑造2-3个有深度的角色\n3. 包含起承转合的情节发展\n4. 结局有意外反转或深刻寓意\n5. 字数：{length}\n6. 风格：{style}"
    },
    {
        category: "营销",
        title: "文案撰写",
        description: "生成营销文案和广告语",
        prompt: "为{product}撰写营销文案，要求：\n1. 标题吸引眼球，引发兴趣\n2. 突出产品独特卖点(USP)\n3. 包含行动号召(CTA)\n4. 目标受众：{audience}\n5. 文案长度：{length}\n6. 渠道：{channel}"
    },
    {
        category: "分析",
        title: "数据分析",
        description: "帮助分析数据和生成报告",
        prompt: "分析以下数据{data}，要求：\n1. 识别关键趋势和模式\n2. 计算关键指标(KPI)\n3. 提供数据可视化建议\n4. 总结主要发现\n5. 提出改进建议\n6. 格式：清晰的报告结构"
    }
];

// 工具类型标签映射
const toolTags = {
    "免费": { class: "free", label: "免费" },
    "免费增值": { class: "freemium", label: "免费增值" },
    "付费": { class: "paid", label: "付费" },
    "开源": { class: "free", label: "开源" }
};

// 导出数据
if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
        aiToolsData,
        categoryInfo,
        promptTemplates,
        toolTags
    };
}
